#services:
#  chroma:
#    image: 'chromadb/chroma:latest'
#    ports:
#      - '8000'
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=postgres'
#      - 'POSTGRES_PASSWORD=admin'
#      - 'POSTGRES_USER=postgres'
#    ports:
#      - '5432:5432'
