spring:
  application:
    name: aluno-service
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  docker:
    compose:
      skip:
        if-file-missing: true
      enabled: false

server:
  servlet:
    context-path: /student-manager

resilience4j:
  circuitbreaker:
    instances:
      addressService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
management:
  health:
    circuitbreakers:
      enabled: true
