spring:
  application:
    name: aluno-service
  datasource:
    url: ${DATA_SOURCE_URL:jdbc:postgresql://db:5432/postgres}
    username: ${DATA_SOURCE_USERNAME:myuser}
    password: ${DATA_SOURCE_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  docker:
    compose:
      enabled: ${IS_DOCKER_ENABLE:true}

server:
  servlet:
    context-path: /student-manager

resilience4j:
  circuitbreaker:
    instances:
      addressService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
management:
  health:
    circuitbreakers:
      enabled: true
